apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: n6ibhvqtk-python 
  janus-idp.io/tekton: n6ibhvqtk-python
  backstage.io/kubernetes-id: n6ibhvqtk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n6ibhvqtk-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  