apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n6ibhvqtk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n6ibhvqtk-python 
  name: n6ibhvqtk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: n6ibhvqtk-python 
